# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My First Jekyll Website
email: cory.r.johnson@cox.net
description: > # this means to ignore newlines until "baseurl:"
  Neil Armstrong is known for the quote "One small step for man, one giant leap for mankind", 
  which is very significant in the sense that no human had walked on the moon before. What is often
  forgotten about this mission is the amount of work and effort put into the project of building 
  the rocket and launching it while mission control monitored almost all aspects of the launch.
  My intention for producing and managing internet based content is similar to this. I want to
  partake in an effort that would achieve a feat that would make a user feel like they just landed
  on the moon within some aspect of their life and this website marks my first step in doing this.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
github_username:  coryj1990

# Build settings
markdown: kramdown
theme: minima
